### ISSUE TITLE
Run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [p32929/pomota#10]
As titled.
I've shifted it to AUR [pomota-bin](https://aur.archlinux.org/packages/pomota-bin)

### Error
When I run the program and press the button,I got these errors:
```
$ pomota
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:230207): GLib-GObject-CRITICAL **: 09:28:23.062: invalid (NULL) pointer instance

(WebKitWebProcess:230207): GLib-GObject-CRITICAL **: 09:28:23.062: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
I can't find any package about `autoaudiosink`.

### Enveriment
OS: EndeavourOS(Arch Linux Based)
Kernel: 6.1.61-1-lts
DE: Cinnamon
gstreamer and lib32-gstreamer: 1.22.6

**Comment by p32929** [comment]
Hi, sorry but I've been running Windows for the past 6-7 years. But I think, I can help. Can you reach out to me by whatsapp/facebook? links are here: https://p32929.github.io/

**Comment by p32929** [comment]
Hi, sorry but I've been running Windows for the past 6-7 years. But I think, I can help. Can you reach out to me by whatsapp/facebook? links are here: https://p32929.github.io/

& also, I don't know who created pomota-bin. its my first time seeing it tbh, but thanks to whoever did it actually

**Comment by zxp19821005** [comment]
@p32929 Thanks for your reply,maybe it's my PC's errors,it run well now.
